%{
Author: Evan McKenzie
Date: November 7, 2021
Class: EE 3160 Signals and Systems
%}

clc;

%constants
J = 0.01;
B = 0.1;
K = 0.01;
R = 0.7;
L = 0.3;


s = tf('s');
DCmotor = K/((J*s+B)*(L*s+R)+K^2)           %transfer function generated by hand
subplot(2,1,1)
step(DCmotor)           %zero input resp
subplot(2,1,2)
impulse(DCmotor)        %zero state resp.